context:
  name: cargo-edit
  version: "0.13.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: "https://github.com/killercup/cargo-edit/archive/v${{ version }}.tar.gz"
  sha256: 8f94d5fd27ec8297728a12172c9ec14ecb55c8b1331049ecc04de3c101f4485f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - cargo-upgrade --help
about:
  homepage: https://killercup.github.io/cargo-edit/cargo_edit/index.html
  summary: 'A utility for managing cargo dependencies from the command line. '
  description: |
    This tool extends [Cargo](http://doc.crates.io/) to allow you to add, remove,
    and upgrade dependencies by modifying your `Cargo.toml` file from the command line.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/killercup/cargo-edit

extra:
  recipe-maintainers:
    - Hofer-Julian
